### ISSUE TITLE
Choosing which collection(s) to expose?

### ISSUE THREAD

**Issue by BrendonKoz** [zerocrates/OaiPmhRepository#27]
Is it possible in the current version of the plugin to choose which collections are able to be exposed to the harvesters through the repository (if so, assuming advanced ini settings)? Our archiving crew is concerned with adding anything that contains copyright and opening up a repository - though they like the idea of sharing with DPLA for certain collections.

**Comment by zerocrates** [comment]
The repository does respect public/private flags on items; no non-public items will be exposed.

On the DPLA side I would assume they can only _harvest_ certain sets, though I'm not sure.

Does that work for you? The repository doesn't really pay much attention to Collections: it exposes them as Sets but items not in any collection at all are exposed and harvestable.

**Comment by BrendonKoz** [comment]
So to clarify: The repository exposes public items only. If the items are private but part of a public collection (and therefore exposed through Omeka's web view), would that mean the items cannot be harvested if the repository is active? If so that very well may work for us.

**Comment by zerocrates** [comment]
Private items are not exposed through Omeka's web interface, no matter what
collection they're in. Only if you're viewing the public side as a logged
in user would you see any private items.

**Comment by BrendonKoz** [comment]
Ah, I've always been logged in while working on it...that makes more sense. So, for our needs that's unfortunately not going to work, but considering our organization also has access to ContentDM it's less important to have the functionality. I personally would just prefer to keep everything in-house (ContentDM is not library-specific for us, it's a state-wide container) but our staff don't mind. I'll consider this closed/answered, thank you!
